EXPERIMENT_NAME = "[FR] [Bordeaux] [galleon] MRIsegmentation"
MLFLOW_URI = "https://mlflow.lewagon.co"
BUCKET_NAME = "galleon-mri"
BUCKET_DATA_PATH = "kaggle_3m"
GDRIVE_DATA_PATH = "/content/drive/MyDrive/MRIsegmentation/"
